markdown:         kramdown
highlighter:      rouge
permalink:        pretty
title:            Kieran Benton
tagline:          'Kieran Benton''s Engineering Blog'
description:      'A brazen two-column <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that pairs a prominent sidebar with uncomplicated content. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              http://www.kieranbenton.com
baseurl:          /
author:
  name:           'Kieran Benton'
  url:            https://twitter.com/kieranbenton
paginate:         5
github:
  repo:           https://github.com/kieranbenton/kieranbenton.github.io
plugins:
  - jekyll-gist
  - jekyll-paginate