markdown:         kramdown
highlighter:      rouge
permalink:        pretty
title:            Kieran Benton
tagline:          'Kieran Benton''s Engineering Blog'
description:      'Kieran Benton is a Dad, former Chief Architect in e-Commerce, former consultant full-stack engineer, now founder. <a href="https://twitter.com/kieranbenton" target="_blank">@kieranbenton</a>.'
url:              http://www.kieranbenton.com
baseurl:          /
author:
  name:           'Kieran Benton'
  url:            https://twitter.com/kieranbenton
github:
  repo:           https://github.com/kieranbenton
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-analytics
paginate:         5
jekyll_analytics:
  GoogleAnalytics:          # Add, if you want to track with Google Analytics
    id: UA-342697-6         # Required - replace with your tracking id
    anonymizeIp: false      # Optional - Default: false - set to true for anonymized tracking
