markdown:         kramdown
highlighter:      rouge
permalink:        pretty
title:            Kieran Benton
tagline:          'Kieran Benton''s Engineering Blog'
url:              https://www.kieranbenton.com
baseurl:          ""
author:
  name:           'Kieran Benton'
  url:            https://twitter.com/kieranbenton
plugins:
  - jekyll-gist
  - jekyll-paginate
paginate:         5